import 'package:hive/hive.dart';

part 'achievement.g.dart'; // Generated by hive_generator

/// Achievement types for gamification
@HiveType(typeId: 10)
enum AchievementType {
  @HiveField(0)
  firstQuiz, // Complete first quiz

  @HiveField(1)
  continentMaster, // Perfect score on a continent

  @HiveField(2)
  streakWarrior, // Login streaks (7/14/30 days)

  @HiveField(3)
  speedster, // Complete quiz quickly

  @HiveField(4)
  explorer, // Try all continents

  @HiveField(5)
  perfectionist, // 100% correct answers in a quiz

  @HiveField(6)
  dedicated, // Multiple quizzes completed (50/100/500)

  @HiveField(7)
  practiceExpert, // Practice mode achievements

  @HiveField(8)
  dailyChampion, // Daily challenge achievements
}

/// Achievement model for gamification system
@HiveType(typeId: 1)
class Achievement extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final String nameKey; // i18n key for achievement name

  @HiveField(2)
  final String descriptionKey; // i18n key for description

  @HiveField(3)
  final String iconPath;

  @HiveField(4)
  final AchievementType type;

  @HiveField(5)
  final int targetValue; // e.g., 7 for 7-day streak

  @HiveField(6)
  bool isUnlocked;

  @HiveField(7)
  DateTime? unlockedAt;

  @HiveField(8)
  int currentProgress;

  Achievement({
    required this.id,
    required this.nameKey,
    required this.descriptionKey,
    required this.iconPath,
    required this.type,
    required this.targetValue,
    this.isUnlocked = false,
    this.unlockedAt,
    this.currentProgress = 0,
  });

  /// Update progress towards achievement
  void updateProgress(int value) {
    if (isUnlocked) return; // Already unlocked

    currentProgress = value;

    // Check if target is reached
    if (currentProgress >= targetValue) {
      unlock();
    } else {
      save();
    }
  }

  /// Unlock the achievement
  void unlock() {
    if (isUnlocked) return; // Already unlocked

    isUnlocked = true;
    unlockedAt = DateTime.now();
    currentProgress = targetValue;
    save();
  }

  /// Get progress percentage
  double get progressPercentage {
    if (targetValue == 0) return 100.0;
    return (currentProgress / targetValue * 100).clamp(0.0, 100.0);
  }

  /// Check if achievement is in progress
  bool get isInProgress => !isUnlocked && currentProgress > 0;

  @override
  String toString() {
    return 'Achievement(id: $id, type: $type, progress: $currentProgress/$targetValue, '
        'unlocked: $isUnlocked)';
  }
}

/// Predefined achievements for the app
class Achievements {
  static final List<Achievement> all = [
    // First Steps
    Achievement(
      id: 'first_quiz',
      nameKey: 'achievement_first_quiz',
      descriptionKey: 'achievement_first_quiz_desc',
      iconPath: 'assets/images/badges/first_quiz.png',
      type: AchievementType.firstQuiz,
      targetValue: 1,
    ),
    Achievement(
      id: 'global_explorer',
      nameKey: 'achievement_global_explorer',
      descriptionKey: 'achievement_global_explorer_desc',
      iconPath: 'assets/images/badges/global_explorer.png',
      type: AchievementType.explorer,
      targetValue: 6, // All 6 continents
    ),

    // Mastery
    Achievement(
      id: 'africa_expert',
      nameKey: 'achievement_africa_expert',
      descriptionKey: 'achievement_africa_expert_desc',
      iconPath: 'assets/images/badges/africa_expert.png',
      type: AchievementType.continentMaster,
      targetValue: 162, // 54 correct * 3 = 162 (perfect score for Africa)
    ),
    Achievement(
      id: 'perfectionist',
      nameKey: 'achievement_perfectionist',
      descriptionKey: 'achievement_perfectionist_desc',
      iconPath: 'assets/images/badges/perfectionist.png',
      type: AchievementType.perfectionist,
      targetValue: 1,
    ),

    // Streaks
    Achievement(
      id: 'week_warrior',
      nameKey: 'achievement_week_warrior',
      descriptionKey: 'achievement_week_warrior_desc',
      iconPath: 'assets/images/badges/streak_7.png',
      type: AchievementType.streakWarrior,
      targetValue: 7,
    ),
    Achievement(
      id: 'fortnight_fighter',
      nameKey: 'achievement_fortnight_fighter',
      descriptionKey: 'achievement_fortnight_fighter_desc',
      iconPath: 'assets/images/badges/streak_14.png',
      type: AchievementType.streakWarrior,
      targetValue: 14,
    ),
    Achievement(
      id: 'monthly_master',
      nameKey: 'achievement_monthly_master',
      descriptionKey: 'achievement_monthly_master_desc',
      iconPath: 'assets/images/badges/streak_30.png',
      type: AchievementType.streakWarrior,
      targetValue: 30,
    ),

    // Speed
    Achievement(
      id: 'speedster',
      nameKey: 'achievement_speedster',
      descriptionKey: 'achievement_speedster_desc',
      iconPath: 'assets/images/badges/speedster.png',
      type: AchievementType.speedster,
      targetValue: 90, // seconds
    ),

    // Dedication
    Achievement(
      id: 'dedicated_learner',
      nameKey: 'achievement_dedicated_learner',
      descriptionKey: 'achievement_dedicated_learner_desc',
      iconPath: 'assets/images/badges/dedicated_50.png',
      type: AchievementType.dedicated,
      targetValue: 50,
    ),
    Achievement(
      id: 'flag_fanatic',
      nameKey: 'achievement_flag_fanatic',
      descriptionKey: 'achievement_flag_fanatic_desc',
      iconPath: 'assets/images/badges/dedicated_100.png',
      type: AchievementType.dedicated,
      targetValue: 100,
    ),
  ];
}
