import 'package:hive/hive.dart';

part 'quiz_session.g.dart'; // Generated by hive_generator

/// Quiz session model for saving mid-quiz progress
@HiveType(typeId: 3)
class QuizSession extends HiveObject {
  @HiveField(0)
  final String sessionId;

  @HiveField(1)
  final String continentId;

  @HiveField(2)
  List<String> flagIds; // IDs of flags in quiz order

  @HiveField(3)
  int currentQuestionIndex;

  @HiveField(4)
  int correctCount;

  @HiveField(5)
  int wrongCount;

  @HiveField(6)
  DateTime startedAt;

  @HiveField(7)
  DateTime? pausedAt;

  @HiveField(8)
  bool isCompleted;

  @HiveField(9)
  Map<String, bool> answeredQuestions; // flagId -> isCorrect

  QuizSession({
    required this.sessionId,
    required this.continentId,
    required this.flagIds,
    this.currentQuestionIndex = 0,
    this.correctCount = 0,
    this.wrongCount = 0,
    DateTime? startedAt,
    this.pausedAt,
    this.isCompleted = false,
    Map<String, bool>? answeredQuestions,
  })  : startedAt = startedAt ?? DateTime.now(),
        answeredQuestions = answeredQuestions ?? {};

  /// Calculate current score using the Kotlin scoring formula: correct * 3 - wrong
  int get currentScore => (correctCount * 3) - wrongCount;

  /// Get total number of questions in this session
  int get totalQuestions => flagIds.length;

  /// Get progress percentage
  double get progressPercentage {
    if (totalQuestions == 0) return 0.0;
    return (currentQuestionIndex / totalQuestions) * 100;
  }

  /// Record an answer
  void recordAnswer(String flagId, bool isCorrect) {
    answeredQuestions[flagId] = isCorrect;

    if (isCorrect) {
      correctCount++;
    } else {
      wrongCount++;
    }

    currentQuestionIndex++;

    // Check if quiz is completed
    if (currentQuestionIndex >= totalQuestions) {
      isCompleted = true;
    }

    // Save to Hive
    save();
  }

  /// Pause the session
  void pause() {
    pausedAt = DateTime.now();
    save();
  }

  /// Resume the session
  void resume() {
    pausedAt = null;
    save();
  }

  /// Mark session as completed
  void complete() {
    isCompleted = true;
    save();
  }

  /// Get elapsed time
  Duration get elapsedTime {
    final endTime = pausedAt ?? DateTime.now();
    return endTime.difference(startedAt);
  }

  /// Check if session is paused
  bool get isPaused => pausedAt != null && !isCompleted;

  /// Check if session is active (not completed and not paused)
  bool get isActive => !isCompleted && !isPaused;

  @override
  String toString() {
    return 'QuizSession(id: $sessionId, continent: $continentId, '
        'progress: $currentQuestionIndex/$totalQuestions, '
        'score: $currentScore, completed: $isCompleted)';
  }
}
