import 'package:hive/hive.dart';

part 'user_progress.g.dart'; // Generated by hive_generator

/// User progress model for tracking quiz performance per continent
@HiveType(typeId: 0)
class UserProgress extends HiveObject {
  @HiveField(0)
  final String continentId;

  @HiveField(1)
  int highScore;

  @HiveField(2)
  int totalQuizzesTaken;

  @HiveField(3)
  int totalCorrectAnswers;

  @HiveField(4)
  int totalWrongAnswers;

  @HiveField(5)
  List<String> learnedFlagIds;

  @HiveField(6)
  List<String> difficultFlagIds;

  @HiveField(7)
  DateTime? lastPlayedAt;

  @HiveField(8)
  bool isUnlocked; // Always true for FREE EXPLORATION mode

  @HiveField(9)
  double completionPercentage;

  UserProgress({
    required this.continentId,
    this.highScore = 0,
    this.totalQuizzesTaken = 0,
    this.totalCorrectAnswers = 0,
    this.totalWrongAnswers = 0,
    List<String>? learnedFlagIds,
    List<String>? difficultFlagIds,
    this.lastPlayedAt,
    this.isUnlocked = true, // FREE EXPLORATION: all continents unlocked by default
    this.completionPercentage = 0.0,
  })  : learnedFlagIds = learnedFlagIds ?? [],
        difficultFlagIds = difficultFlagIds ?? [];

  /// Update progress after completing a quiz
  void updateAfterQuiz({
    required int score,
    required int correct,
    required int wrong,
    required List<String> newLearnedFlags,
    required List<String> newDifficultFlags,
    required int totalFlagsInContinent,
  }) {
    // Update high score
    if (score > highScore) {
      highScore = score;
    }

    // Update counters
    totalQuizzesTaken++;
    totalCorrectAnswers += correct;
    totalWrongAnswers += wrong;

    // Add newly learned flags (answered correctly)
    for (final flagId in newLearnedFlags) {
      if (!learnedFlagIds.contains(flagId)) {
        learnedFlagIds.add(flagId);
      }
    }

    // Add flags that were answered incorrectly
    for (final flagId in newDifficultFlags) {
      if (!difficultFlagIds.contains(flagId)) {
        difficultFlagIds.add(flagId);
      }
    }

    // Update completion percentage
    completionPercentage = (learnedFlagIds.length / totalFlagsInContinent) * 100;

    // Update last played timestamp
    lastPlayedAt = DateTime.now();

    // Save to Hive
    save();
  }

  /// Calculate average accuracy
  double get accuracy {
    final total = totalCorrectAnswers + totalWrongAnswers;
    if (total == 0) return 0.0;
    return (totalCorrectAnswers / total) * 100;
  }

  /// Get formatted accuracy string
  String get formattedAccuracy => '${accuracy.toStringAsFixed(1)}%';

  /// Get formatted completion percentage string
  String get formattedCompletion => '${completionPercentage.toStringAsFixed(0)}%';

  @override
  String toString() {
    return 'UserProgress(continent: $continentId, highScore: $highScore, '
        'quizzes: $totalQuizzesTaken, accuracy: $formattedAccuracy, '
        'completion: $formattedCompletion)';
  }
}
